"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
ON_RENDER = os.environ.get('RENDER', '').lower() == 'true'
DEBUG = os.environ.get('DEBUG', 'false' if ON_RENDER else 'true').lower() == 'true'
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if ON_RENDER or not DEBUG:
        raise ImproperlyConfigured('운영 환경에는 SECRET_KEY 환경변수가 필요합니다.')
    SECRET_KEY = 'django-insecure-local-development-only'

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = [host.strip() for host in os.environ.get(
    'ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver' if DEBUG else ''
).split(',') if host.strip()]
RENDER_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if RENDER_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_HOSTNAME)
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get(
    'CSRF_TRUSTED_ORIGINS', ''
).split(',') if origin.strip()]
if RENDER_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_HOSTNAME}')
if ON_RENDER:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = ON_RENDER and not DEBUG
SECURE_REDIRECT_EXEMPT = [r'^healthz/$', r'^readyz/$']
BATCH_SCHEDULER_ENABLED = os.environ.get('BATCH_SCHEDULER_ENABLED', 'true').lower() == 'true'
CSV_WARMUP_ENABLED = os.environ.get('CSV_WARMUP_ENABLED', 'true').lower() == 'true'
CSV_REFRESH_INTERVAL_SECONDS = float(os.environ.get('CSV_REFRESH_INTERVAL_SECONDS', '5'))
# 첫 적재가 이 시간을 넘기면 안내 화면을 걷고 요청이 직접 읽게 둔다. 기다리게만
# 하는 화면보다 느리더라도 응답하는 편이 낫다.
CSV_READY_TIMEOUT_SECONDS = float(os.environ.get('CSV_READY_TIMEOUT_SECONDS', '120'))


# Application definition

INSTALLED_APPS = [
    'app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'app.runtime.diagnostics.RequestDiagnosticsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 정적 파일 다음에 둔다. 안내 화면이 뜨는 상황에서도 자산 제공은 살아 있어야 한다.
    'app.runtime.middleware.CsvReadinessMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Keep stable filenames: map scripts resolve adjacent GeoJSON files by URL.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}
STATICFILES_FINDERS = [
    'app.common.staticfiles.PortableFileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
# The image folder sits beside the project rather than inside static/, so it is
# mounted under a prefix and referenced as {% static 'image/...' %}.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    ('image', BASE_DIR.parent / 'image'),
    ('fonts', BASE_DIR.parent / 'fonts'),
    ('theme', BASE_DIR.parent / 'theme'),
]
# 웹 화면은 배치가 생성한 서울 전용 CSV만 읽는다.
DATA_DIR = BASE_DIR.parent / 'data' / 'Batch'

# 대시보드는 서울 전용이므로 현재 서비스 배치 범위의 기본값은 seoul이다.
# 전국 데이터로 전환할 때 환경변수 BATCH_REGION_KEY=national을 지정한다.
BATCH_REGION_KEY = os.environ.get('BATCH_REGION_KEY', 'seoul').strip().lower()

# 데이터 반영 대상은 csv 또는 db로 전환할 수 있다.
# 현재 서비스 저장소는 CSV이므로 기본값은 csv이며, DB 모델이 준비되면
# 환경변수 BATCH_STORAGE_MODE=db와 BATCH_DB_WRITER의 함수 경로를 지정한다.
BATCH_STORAGE_MODE = os.environ.get('BATCH_STORAGE_MODE', 'csv').strip().lower()
BATCH_DB_WRITER = os.environ.get('BATCH_DB_WRITER', '').strip()

DATA_FILES = {
    'programs': f'public_sports_program_{BATCH_REGION_KEY}.csv',
    'usage': f'sports_voucher_usage_{BATCH_REGION_KEY}.csv',
    'facilities': f'sports_facility_status_{BATCH_REGION_KEY}.csv',
    'transit': f'facility_transit_{BATCH_REGION_KEY}.csv',
}

# 프로그램 검색의 지역 선택 UI를 fixed 또는 selectable로 전환한다.
# 현재 서울 전용 CSV에서는 fixed로 지역 선택을 숨기고 시군구만 표시한다.
# 전국 CSV로 확장할 때 selectable로 바꾸면 기존 시도 선택 기능이 다시 나타난다.
PROGRAM_REGION_FILTER_MODE = os.environ.get(
    'PROGRAM_REGION_FILTER_MODE', 'fixed'
).strip().lower()

# 시설 검색도 서울 전용 자료에서는 지역 항목에 구 목록만 표시한다.
# 전국 CSV로 전환할 때 selectable로 바꾸면 시도와 시군구 선택을 함께 표시한다.
FACILITY_REGION_FILTER_MODE = os.environ.get(
    'FACILITY_REGION_FILTER_MODE', 'fixed'
).strip().lower()

# APScheduler의 실행 요일과 시각은 이 설정만 바꿔 조정한다.
# 요일은 mon, tue, wed, thu, fri, sat, sun 중 하나를 사용한다.
# 시간은 24시간 형식이며, 21시 33분은 hour를 21, minute을 33으로 설정한다.
BATCH_SCHEDULE = {
    'day_of_week': 'sun',
    'hour': 0,
    'minute': 0,
}


# External policy listing
# The crawler reads nothing but this source, so every part of the address and
# the markup it depends on lives here rather than in the code.

POLICY_SOURCE = {
    'name': '문화체육관광부 체육정책',
    'base_url': 'https://www.mcst.go.kr/site/s_policy/dept/',
    'list_path': 'deptList.jsp?pType=07',
    'table_class': 'board',
    'cell_class': 'tit_wrap',
    'limit': 10,
    'timeout': 6,
    'cache_seconds': 900,
    'retry_seconds': 60,
    'max_bytes': 2_000_000,
    'user_agent': 'SPORT-INSIGHT/1.0 (public policy listing reader)',
}
LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Render collects stderr. Django's default console handler is disabled when
# DEBUG=False, so explicitly route server errors (including exc_info) here.
# Do not format request objects, headers, cookies, or form bodies into logs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'server': {
            'format': '{asctime} {levelname} {name} pid={process} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stderr',
            'formatter': 'server',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'], 'level': 'INFO', 'propagate': False,
        },
        'django.server': {
            'handlers': ['console'], 'level': 'INFO', 'propagate': False,
        },
        'app': {
            'handlers': ['console'], 'level': 'INFO', 'propagate': False,
        },
        'apscheduler': {
            'handlers': ['console'], 'level': 'INFO', 'propagate': False,
        },
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
}

# 장애 진단 후 환경변수를 false로 설정해 요청별 로그를 끌 수 있다.
CSV_DIAGNOSTICS_ENABLED = os.environ.get('CSV_DIAGNOSTICS_ENABLED', 'true').lower() == 'true'
LOGGING['loggers']['app.runtime.diagnostics'] = {
    'handlers': ['console'], 'level': 'INFO', 'propagate': False,
}
